# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Look in ~/.oh-my-zsh/themes/
ZSH_THEME="my"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git osx)

source ${ZSH}/oh-my-zsh.sh

# User configuration
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
MANPATH="/usr/local/man:${MANPATH}"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# set language environment
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN.UTF-8

# set default editor
export EDITOR='vim'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

export LINODE="139.162.125.45"
export WORKSTATION="192.168.199.190"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes.
alias ll="ls -lhGF"
alias la="ls -lahGF"
alias cp="cp -i"
alias clonesite="wget -c -r -np -k -L -p"

# Diffrent system has diffrent configure
# for macbook-pro with osx
if [ $(uname) = "Darwin" ]; then
    # for osx
    alias wwwroot="cd /Library/WebServer/Documents"
    alias cleanqq="rm -rf /Users/lihuanpeng/Library/Containers/com.tencent.qq/Data/Library/Application\ Support/QQ/2705313595/Image"
    # those two lines for CUDA environment
    CUDA_PATH="/Developer/NVIDIA/CUDA-8.0"
    export PATH="${CUDA_PATH}/bin:${PATH}"
    export LD_LIBRARY_PATH="${CUDA_PATH}/lib:${LD_LIBRARY_PATH}"

    # for Qt env
    export QTDIR="/Applications/Qt5.9.1/5.9/clang_64"
    export PATH="${QTDIR}/bin:${PATH}"
    export LD_LIBRARY_PATH="${QTDIR}/lib:${LD_LIBRARY_PATH}"
fi

if [ $(uname) = "Linux" ]; then
    # tesseract
    export TESSDATA_PREFIX="/usr/local/share/tessdata"
    export LD_LIBRARY_PATH="/lib:/lib64:/usr/lib:/usr/local/lib"

    # Qt env
    export QT_SELECT="Qt5.9"
    export QTDIR="/opt/Qt5.9.1/5.9/gcc_64"
    export PATH="${PATH}:${QTDIR}/bin"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${QTDIR}/lib"

    # for java
    export JAVA_HOME="/usr/lib/jvm/default-java"
    export JRE_HOME="${JAVA_HOME}/jre"
    export CLASSPATH="${JAVA_HOME}/lib:${JRE_HOME}/lib"
    export PATH="${PATH}:${JAVA_HOME}/bin"

    # path for anaconda3
    export PATH="/opt/anaconda3/bin:${PATH}"

    if [ $(hostname) = "workstation" ]; then
        # alias
        alias i3config="vim ~/.i3/config"
        # those two lines for CUDA environment
        CUDA_PATH="/usr/local/cuda"
        export PATH="${PATH}:${CUDA_PATH}/bin"
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CUDA_PATH}/lib64"
    fi
fi

# export environments
export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'

#end of file
