# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Look in ~/.oh-my-zsh/themes/
ZSH_THEME="my"

# Used plugins
plugins=(git osx)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

# bootstrap zsh
source $ZSH/oh-my-zsh.sh

# set language environment
# export LANG=zh_CN.UTF-8

# set default editor
export EDITOR='vim'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# my linode IP
export LINODE="139.162.125.45"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes.
alias ll="ls -lhGF"
alias la="ls -lahGF"
alias cp="cp -i"
alias workstation="ssh lihuanpeng@192.168.199.190"
alias clonesite="wget -c -r -np -k -L -p"

# Diffrent system has diffrent configure
# for macbook-pro with osx
if [ $(uname) = "Darwin" ]; then
    # for osx
    alias wwwroot="cd /Library/WebServer/Documents"
    alias cleanqq="rm -rf /Users/lihuanpeng/Library/Containers/com.tencent.qq/Data/Library/Application\ Support/QQ/2705313595/Image"
    # those two lines for CUDA environment
    export PATH=/Developer/NVIDIA/CUDA-8.0/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}
    # for Qt env
fi

# for workstation with debian.
if [ $(uname) = "Linux" ]; then
    # those two lines for CUDA environment
    export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    # for Qt env
    export QTDIR=/opt/Qt/5.8/gcc_64
    export PATH=$PATH:$QTDIR/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$QTDIR/lib
fi

# end of file
