# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Look in ~/.oh-my-zsh/themes/
ZSH_THEME="my"

# Used plugins
plugins=(git osx)

# User configuration
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
MANPATH="/usr/local/man:${MANPATH}"

# bootstrap zsh
source ${ZSH}/oh-my-zsh.sh

# set language environment
# export LANG=zh_CN.UTF-8

# set default editor
export EDITOR='vim'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# my linode IP
export LINODE="139.162.125.45"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes.
alias ll="ls -lhGF"
alias la="ls -lahGF"
alias cp="cp -i"
alias workstation="ssh lihuanpeng@192.168.199.190"
alias clonesite="wget -c -r -np -k -L -p"



# Diffrent system has diffrent configure
# for macbook-pro with osx
if [ $(uname) = "Darwin" ]; then
    DOTFILE_PATH="/Users/lihuanpeng/.dotfiles"
    export QTVERSION=4
    source "${DOTFILE_PATH}/zsh/macOS.sh"
fi

# for workstation with debian.
if [ $(uname) = "Linux" ]; then
    DOTFILE_PATH="/home/lihuanpeng/.dotfiles"
    export QTVERSION=4
    source "${DOTFILE_PATH}/zsh/debian.sh"
fi

# export environments
export PATH
export LD_LIBRARY_PATH
export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'

 #end of file
